services:
  - type: web
    name: flotation-quality-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: GITHUB_TOKEN
        sync: false
